#[cfg(target_os = "linux")]
pub const AF_PACKET: i32 = 17;
#[cfg(target_os = "linux")]
pub const SOCK_RAW: i32 = 3;
#[cfg(target_os = "linux")]
pub const ETH_P_ARP: i32 = 0x0806;
#[cfg(target_os = "linux")]
pub const ETH_P_ALL: i32 = 0x0003;
#[cfg(target_os = "linux")]
pub const ETH_P_IP: i32 = 0x0800;
#[cfg(target_os = "linux")]
pub const ARPHRD_ETHER: u16 = 1;
#[cfg(target_os = "linux")]
pub const SIOCGIFHWADDR: u64 = 0x8927;
#[cfg(target_os = "linux")]
pub const SIOCGIFINDEX: u64 = 0x8933;
#[cfg(target_os = "linux")]
pub const SIOCGIFADDR: u64 = 0x8915;
#[cfg(target_os = "linux")]
pub const PACKET_BROADCAST: u8 = 1;
#[cfg(target_os = "windows")]
pub const PCAP_OPENFLAG_PROMISCUOUS: i32 = 1;
#[cfg(target_os = "windows")]
pub type TimeT = i64; // Should be changed after 292 billion years
